#!/bin/sh
# SPDX-License-Identifier: BSD-3-Clause-Clear
 
# Base directory of Runner
BASE_DIR="$(CDPATH= cd -- "$(dirname "$0")" >/dev/null 2>&1 && pwd)"
export TOOLS="${BASE_DIR}/utils"
export __RUNNER_SUITES_DIR="${BASE_DIR}/suites"
